server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: "jboss-logs"
    static_configs:
      - targets:
          - localhost
        labels:
          job: "jboss"
          env: "ativo"
          __path__: "/var/log/jboss/ativo/log.txt"

      - targets:
          - localhost
        labels:
          job: "jboss"
          env: "inativo"
          __path__: "/var/log/jboss/inativo/log.txt"

  - job_name: "tomcat-logs"
    static_configs:
      - targets:
          - localhost
        labels:
          job: "tomcat"
          env: "ativo"
          __path__: "/var/log/tomcat/ativo/log.txt"

      - targets:
          - localhost
        labels:
          job: "tomcat"
          env: "inativo"
          __path__: "/var/log/tomcat/inativo/log.txt"
