Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.hostname = "estagio-Esig"
    config.vm.network "public_network"
    config.vm.provider "virtualbox" do |v|
      v.memory = 3072
      v.cpus = 2
    end
  end
