version: '3.8'

services:
  tomcat:
    image: tomcat:latest
    container_name: tomcat-server
    volumes:
      - ./tomcat:/usr/local/tomcat/webapps/ROOT  # Mapeia o diretório tomcat para o diretório ROOT do Tomcat
    ports:
      - "8081:8080"  # HTTP para aplicações (mapeia 8081 no host para 8080 no contêiner)
    networks:
      - app-network

networks:
  app-network:
    driver: bridge